//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleStockAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class MsCategory
    {
        public MsCategory()
        {
            this.MsProducts = new HashSet<MsProduct>();
        }
    
        public int ProductCategoryID { get; set; }
        public string ProductCategoryName { get; set; }

        //for handling reference loop Entity Framework
        [JsonIgnore]
        public virtual ICollection<MsProduct> MsProducts { get; set; }
    }
}
