//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleStockAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsProduct
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductSize { get; set; }
        public string ProductColor { get; set; }
        public int ProductPrice { get; set; }
        public int ProductCategoryID { get; set; }

        public virtual MsCategory MsCategory { get; set; }
    }
}
